apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
  labels:
    deployment: ${NAME}${SUFFIX}
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
    selector:
      # deploymentconfig: ${NAME}${SUFFIX}
      matchLabels:
          deployment: ${NAME}${SUFFIX}
    stringData:
      ftp-user: "${FTP_USER}"
      ftp-password: "${FTP_PASSWORD}"
    type: Opaque
parameters:
  - name: NAME
    displayName: Name
    description: Name
    required: true
    value: ftp
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "-dev"
  - name: FTP_USER
    displayName: FTP_USER
    description: FTP_USER
    required: true
  - name: FTP_PASSWORD
    displayName: FTP_PASSWORD
    description: FTP_PASSWORD
    required: true
