apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${PROJECT_NAME}
labels:
  template: ccw-deploy
objects:
  - apiVersion: v1 #is: ccw
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        shared: "true"
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1 #dc: ccw
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
      strategy:
        activeDeadlineSeconds: 21600
        rollingParams:
          intervalSeconds: 1
          maxSurge: 1
          maxUnavailable: 1
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          creationTimestamp: null
          labels:
            deploymentconfig: ${NAME}${SUFFIX}
        spec:
          containers:
            - image: ${NAME}:${VERSION}
              name: ccw
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              env:
                - name: ConnectionStrings__Schoolbus
                  valueFrom:
                    secretKeyRef:
                      name: "${PROJECT_NAME}-${DB_NAME}-${ENV}"
                      key: connection-string
                - name: CCWInitializationFile
                  value: "/ccwsecrets/ccw.json"
                - name: ASPNETCORE_ENVIRONMENT
                  value: Development
              volumeMounts:
                - name: ccw-secret-volume
                  mountPath: "/ccwsecrets"
                  readOnly: true
          volumes:
            - name: ccw-secret-volume
              secret:
                secretName: ccw-secret
                defaultMode: 420
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - ccw
            from:
              kind: ImageStreamTag
              name: ${NAME}:${VERSION}
          type: ImageChange
        - type: ConfigChange
  - apiVersion: v1 #service: ccw
    kind: Service
    metadata:
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    spec:
      ports:
        - name: web
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
parameters:
  - description: Name of the project (SCHOOLBUS)
    displayName: PROJECT_NAME
    name: PROJECT_NAME
    required: true
    value: "sb"
  - description: A name used for all objects
    displayName: Name
    name: NAME
    required: true
    value: "ccw"
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "-dev"
  - description: Environment short name (dev,test,uat,prod)
    displayName: ENV
    name: ENV
    required: false
    value: "dev"
  - description: A version used for the image tags
    displayName: version
    name: VERSION
    required: true
    value: "v1.4.0"
  - description: The ASP Net Core deployment environment setting
    displayName: AspNetCore Environment
    name: ASPNETCORE_ENVIRONMENT
    required: true
    value: "Development"
  - description: SOURCE_REPOSITORY_URL
    displayName: SOURCE_REPOSITORY_URL
    name: SOURCE_REPOSITORY_URL
    required: false
    value: ""
  - description: SOURCE_REPOSITORY_REF
    displayName: SOURCE_REPOSITORY_REF
    name: SOURCE_REPOSITORY_REF
    required: false
    value: ""
  - name: DB_NAME
    displayName: DB Name
    description:
      The name assigned to all of the CCW microservice objects defined in
      this template.
    required: true
    value: db
